[package]
name = "m6502_basic_rs"
version = "1.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
lazy_static = "1"
regex = "1"
anyhow = "1"
ctrlc = "3"
rustyline = "17.0.1"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
